name: Build

on:
  push:
    branches:
      - '1.*'
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build # Have to run processing first so the list.json exists to be included in the the deploy
        run: |
          npm ci --prefix processing 
          npm ci --prefix site
          ./build_all_branches.sh

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: public

      - name: Gotify Success Notification
        if: success()
        uses: eikendev/gotify-action@master
        with:
          gotify_api_base: ${{ secrets.GOTIFY_API_BASE }}
          gotify_app_token: ${{ secrets.GOTIFY_APP_TOKEN }}
          notification_title: 'Build & Deploy Successful - kasm-registry'
          notification_message: 'Site built and deployed to GitHub Pages successfully.'

      - name: Gotify Failure Notification
        if: failure()
        uses: eikendev/gotify-action@master
        with:
          gotify_api_base: ${{ secrets.GOTIFY_API_BASE }}
          gotify_app_token: ${{ secrets.GOTIFY_APP_TOKEN }}
          notification_title: 'Build & Deploy Failed - kasm-registry'
          notification_message: 'The build and deploy workflow has failed. ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}'
          notification_priority: 5
  otel:
    permissions:
      contents: read # Required. To access the private repository
      actions: read # Required. To read workflow runs
      pull-requests: read # Optional. To read PR labels
      checks: read # Optional. To read run annotations
    if: always()
    name: OpenTelemetry Export Trace
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Export workflow
        uses: corentinmusard/otel-cicd-action@v4
        with:
          otlpEndpoint: ${{ secrets.OTLP_ENDPOINT }}
          otlpHeaders: ${{ secrets.OTLP_HEADERS }}
          otlpAuthorization: ${{ secrets.OTLP_AUTH_TOKEN }}
          otelToken: ${{ secrets.OTEL_TOKEN }}
